/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List alerts */
        get: operations["list_alerts_api_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge an alert */
        post: operations["ack_alert_api_v1_alerts__alert_id__ack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss an alert with reason */
        post: operations["dismiss_alert_api_v1_alerts__alert_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Useful / not useful */
        post: operations["alert_feedback_api_v1_alerts__alert_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/copilot/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask the copilot (SSE stream) */
        post: operations["copilot_chat_api_v1_copilot_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/correlation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Correlation panel data */
        get: operations["correlation_api_v1_correlation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List documents */
        get: operations["list_documents_api_v1_documents_get"];
        put?: never;
        /** Upload report files and start ingestion */
        post: operations["upload_documents_api_v1_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document metadata and status */
        get: operations["get_document_api_v1_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Original uploaded file */
        get: operations["get_file_api_v1_documents__document_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/pages/{page_no}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Page image and text spans for evidence highlighting */
        get: operations["get_page_api_v1_documents__document_id__pages__page_no__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/pages/{page_no}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rendered page image (PNG) */
        get: operations["get_page_image_api_v1_documents__document_id__pages__page_no__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-run ingestion for a document */
        post: operations["reprocess_api_v1_documents__document_id__reprocess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search drilling events */
        get: operations["list_events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/formations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Formation dictionary */
        get: operations["get_formations_api_v1_formations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mitigation effectiveness ranking (USP 2) */
        get: operations["ledger_api_v1_ledger_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated user */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service metadata and component build status */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start/stop/speed a replay session */
        post: operations["replay_api_v1_replay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/offset-brief/{well_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Offset Risk Brief (PDF) */
        get: operations["offset_brief_api_v1_reports_offset_brief__well_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Low-confidence extractions awaiting review */
        get: operations["list_review_queue_api_v1_review_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/review-queue/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept, correct or reject */
        post: operations["review_item_api_v1_review_queue__item_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hybrid document search */
        get: operations["search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wells": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List and filter wells */
        get: operations["get_wells_api_v1_wells_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wells/{well_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Well 360 summary */
        get: operations["get_well_api_v1_wells__well_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wells/{well_id}/offsets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Offset wells within a radius */
        get: operations["get_offsets_api_v1_wells__well_id__offsets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wells/{well_id}/risk-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Offset prior risk by depth */
        get: operations["get_risk_profile_api_v1_wells__well_id__risk_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wells/{well_id}/trajectory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Survey stations and 3D path */
        get: operations["get_trajectory_api_v1_wells__well_id__trajectory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness: the process is up */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness: database (with extensions), Redis and object storage reachable */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Alignment
         * @enum {string}
         */
        Alignment: "TVDSS" | "FLATTEN_ON_TOP" | "FORMATION_RELATIVE";
        /** Body_upload_documents_api_v1_documents_post */
        Body_upload_documents_api_v1_documents_post: {
            /** Files */
            files: string[];
        };
        /** Component */
        Component: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Phase */
            phase: string;
            /** Stage */
            stage: string;
            /**
             * Status
             * @enum {string}
             */
            status: "planned" | "in_progress" | "built";
        };
        /** ComponentStatus */
        ComponentStatus: {
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Latency Ms */
            latency_ms: number;
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
        };
        /** CurrentUser */
        CurrentUser: {
            /** Name */
            name: string;
            /** Roles */
            roles: ("viewer" | "field_engineer" | "rtmac_engineer" | "drilling_engineer" | "data_steward" | "admin")[];
            /** User Id */
            user_id: string;
        };
        /** DataQuality */
        DataQuality: {
            /** Checks */
            checks: components["schemas"]["QualityCheck"][];
            /** Score */
            score: number;
        };
        /** DocumentDetail */
        DocumentDetail: {
            /** Content Type */
            content_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Doc Type */
            doc_type: string | null;
            /** Error */
            error: string | null;
            /** Filename */
            filename: string;
            /** Id */
            id: number;
            /** Ingest Status */
            ingest_status: string;
            /** Page Count */
            page_count: number | null;
            /** Pages */
            pages: components["schemas"]["PageSummary"][];
            /** Processed At */
            processed_at: string | null;
            /** Raw Well Name */
            raw_well_name: string | null;
            /** Report Date */
            report_date: string | null;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** Synthetic */
            synthetic: boolean;
            /** Uploaded By */
            uploaded_by: string | null;
            /** Well Id */
            well_id: number | null;
            /** Well Name */
            well_name: string | null;
        };
        /** DocumentList */
        DocumentList: {
            /** Items */
            items: components["schemas"]["DocumentSummary"][];
            /** Status Counts */
            status_counts: {
                [key: string]: number;
            };
            /** Total */
            total: number;
        };
        /** DocumentSummary */
        DocumentSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Doc Type */
            doc_type: string | null;
            /** Error */
            error: string | null;
            /** Filename */
            filename: string;
            /** Id */
            id: number;
            /** Ingest Status */
            ingest_status: string;
            /** Page Count */
            page_count: number | null;
            /** Processed At */
            processed_at: string | null;
            /** Raw Well Name */
            raw_well_name: string | null;
            /** Report Date */
            report_date: string | null;
            /** Size Bytes */
            size_bytes: number;
            /** Synthetic */
            synthetic: boolean;
            /** Well Id */
            well_id: number | null;
            /** Well Name */
            well_name: string | null;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /**
             * Details
             * @default {}
             */
            details: {
                [key: string]: unknown;
            };
            /** Message */
            message: string;
            /** Request Id */
            request_id?: string | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** FormationOut */
        FormationOut: {
            /** Basin */
            basin: string;
            /** Id */
            id: number;
            /** Lithology */
            lithology: string | null;
            /** Name */
            name: string;
            /** Strat Order */
            strat_order: number;
            /** Synonyms */
            synonyms: string[];
        };
        /** FormationTopOut */
        FormationTopOut: {
            /** Formation */
            formation: string;
            /** Strat Order */
            strat_order: number;
            /** Top Md M */
            top_md_m: number;
            /** Top Tvd M */
            top_tvd_m: number;
            /** Top Tvdss M */
            top_tvdss_m: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Meta */
        Meta: {
            /** Backend Phase */
            backend_phase: string;
            /** Components */
            components: components["schemas"]["Component"][];
            /** Env */
            env: string;
            /** Git Sha */
            git_sha: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /** OffsetOut */
        OffsetOut: {
            /** Bearing Deg */
            bearing_deg: number | null;
            /** Distance M */
            distance_m: number;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Synthetic */
            synthetic: boolean;
            /** Td Md M */
            td_md_m: number | null;
            /** Well Id */
            well_id: number;
            /** Well Type */
            well_type: string | null;
        };
        /** OffsetsOut */
        OffsetsOut: {
            /** Formation */
            formation: string | null;
            /** Mode */
            mode: string;
            /** Offsets */
            offsets: components["schemas"]["OffsetOut"][];
            /** Radius Km */
            radius_km: number;
            /** Well Id */
            well_id: number;
        };
        /** PageOut */
        PageOut: {
            /** Document Id */
            document_id: number;
            /** Height Px */
            height_px: number;
            /** Image Url */
            image_url: string;
            /** Ocr Mean Conf */
            ocr_mean_conf: number | null;
            /** Ocr Used */
            ocr_used: boolean;
            /** Page No */
            page_no: number;
            /** Spans */
            spans: components["schemas"]["SpanOut"][];
            /** Width Px */
            width_px: number;
        };
        /** PageSummary */
        PageSummary: {
            /** Ocr Mean Conf */
            ocr_mean_conf: number | null;
            /** Ocr Used */
            ocr_used: boolean;
            /** Page No */
            page_no: number;
            /** Span Count */
            span_count: number;
        };
        /** PathPoint */
        PathPoint: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Tvdss M */
            tvdss_m: number;
        };
        /**
         * ProximityMode
         * @enum {string}
         */
        ProximityMode: "SURFACE" | "AT_FORMATION" | "CLOSEST_APPROACH";
        /** QualityCheck */
        QualityCheck: {
            /** Detail */
            detail: string;
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
        };
        /** ReadinessReport */
        ReadinessReport: {
            /** Components */
            components: components["schemas"]["ComponentStatus"][];
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
        };
        /** SpanOut */
        SpanOut: {
            /** Bbox */
            bbox: number[];
            /** Conf */
            conf: number | null;
            /** Id */
            id: number;
            /** Line No */
            line_no: number;
            /** Text */
            text: string;
        };
        /** StationOut */
        StationOut: {
            /** Azi Deg */
            azi_deg: number;
            /** Dls Deg 30M */
            dls_deg_30m: number;
            /** East M */
            east_m: number;
            /** Inc Deg */
            inc_deg: number;
            /** Md M */
            md_m: number;
            /** North M */
            north_m: number;
            /** Tvd M */
            tvd_m: number;
            /** Tvdss M */
            tvdss_m: number;
        };
        /** TrajectoryOut */
        TrajectoryOut: {
            /** Assumed */
            assumed: boolean;
            /** Crs Epsg */
            crs_epsg: number;
            /** Path */
            path: components["schemas"]["PathPoint"][];
            /** Stations */
            stations: components["schemas"]["StationOut"][];
            /** Well Id */
            well_id: number;
            /** Wellbore Id */
            wellbore_id: number;
        };
        /** UploadResult */
        UploadResult: {
            /** Document Id */
            document_id: number;
            /** Duplicate */
            duplicate: boolean;
            /** Filename */
            filename: string;
            /** Sha256 */
            sha256: string;
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WellDetail */
        WellDetail: {
            /** Aliases */
            aliases: string[];
            /** Completion Date */
            completion_date: string | null;
            /** Crs Epsg */
            crs_epsg: number;
            data_quality: components["schemas"]["DataQuality"];
            /** Datum Assumed */
            datum_assumed: boolean;
            /** Document Count */
            document_count: number;
            /** Field */
            field: string;
            /** Formation Tops */
            formation_tops: components["schemas"]["FormationTopOut"][];
            /** Gl Elev M */
            gl_elev_m: number | null;
            /** Id */
            id: number;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Name */
            name: string;
            /** Profile */
            profile: string | null;
            /** Rig Name */
            rig_name: string | null;
            /** Rkb Elev M */
            rkb_elev_m: number | null;
            /** Spud Date */
            spud_date: string | null;
            /** Status */
            status: string;
            /** Synthetic */
            synthetic: boolean;
            /** Td Md M */
            td_md_m: number | null;
            /** Trajectory Assumed */
            trajectory_assumed: boolean;
            /** Units System */
            units_system: string | null;
            /** Well Type */
            well_type: string | null;
        };
        /** WellList */
        WellList: {
            /** Items */
            items: components["schemas"]["WellSummary"][];
            /** Total */
            total: number;
        };
        /** WellSummary */
        WellSummary: {
            /** Document Count */
            document_count: number;
            /** Field */
            field: string;
            /** Id */
            id: number;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Name */
            name: string;
            /** Profile */
            profile: string | null;
            /** Spud Date */
            spud_date: string | null;
            /** Status */
            status: string;
            /** Synthetic */
            synthetic: boolean;
            /** Td Md M */
            td_md_m: number | null;
            /** Well Type */
            well_type: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_alerts_api_v1_alerts_get: {
        parameters: {
            query?: {
                well_id?: number | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Planned, not implemented in this phase */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ack_alert_api_v1_alerts__alert_id__ack_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Planned, not implemented in this phase */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    dismiss_alert_api_v1_alerts__alert_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Planned, not implemented in this phase */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    alert_feedback_api_v1_alerts__alert_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Planned, not implemented in this phase */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    copilot_chat_api_v1_copilot_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Planned, not implemented in this phase */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    correlation_api_v1_correlation_get: {
        parameters: {
            query: {
                wells: number[];
                align?: components["schemas"]["Alignment"];
                top?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Planned, not implemented in this phase */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_documents_api_v1_documents_get: {
        parameters: {
            query?: {
                well_id?: number | null;
                status?: string | null;
                doc_type?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_documents_api_v1_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_documents_api_v1_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_api_v1_documents__document_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_api_v1_documents__document_id__pages__page_no__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
                page_no: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_image_api_v1_documents__document_id__pages__page_no__image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
                page_no: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reprocess_api_v1_documents__document_id__reprocess_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_v1_events_get: {
        parameters: {
            query?: {
                event_type?: string | null;
                formation?: string | null;
                well_id?: number | null;
                radius_km?: number | null;
                tvdss_from_m?: number | null;
                tvdss_to_m?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Planned, not implemented in this phase */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_formations_api_v1_formations_get: {
        parameters: {
            query?: {
                basin?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ledger_api_v1_ledger_get: {
        parameters: {
            query: {
                event_type: string;
                formation?: string | null;
                basin?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Planned, not implemented in this phase */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
        };
    };
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    replay_api_v1_replay_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Planned, not implemented in this phase */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    offset_brief_api_v1_reports_offset_brief__well_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                well_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Planned, not implemented in this phase */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_review_queue_api_v1_review_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Planned, not implemented in this phase */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    review_item_api_v1_review_queue__item_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Planned, not implemented in this phase */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_api_v1_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Planned, not implemented in this phase */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_wells_api_v1_wells_get: {
        parameters: {
            query?: {
                field?: string | null;
                status?: string | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WellList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_well_api_v1_wells__well_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                well_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WellDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_offsets_api_v1_wells__well_id__offsets_get: {
        parameters: {
            query?: {
                radius_km?: number;
                mode?: components["schemas"]["ProximityMode"];
                formation?: string | null;
            };
            header?: never;
            path: {
                well_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OffsetsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Planned, not implemented in this phase */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_risk_profile_api_v1_wells__well_id__risk_profile_get: {
        parameters: {
            query?: {
                sigma_km?: number | null;
            };
            header?: never;
            path: {
                well_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Planned, not implemented in this phase */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_trajectory_api_v1_wells__well_id__trajectory_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                well_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrajectoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessReport"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessReport"];
                };
            };
        };
    };
}
